//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK63CNTT2_63131016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public string MaTV { get; set; }
        public string HoTV { get; set; }
        public string TenTV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string AnhTV { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string MaTinh { get; set; }
    
        public virtual TINH TINH { get; set; }
    }
}
